** Context
Students new to an Operating systems course are often overwhelmed by the vastness and the depth of the course. And the course content often doesn't provide the right abstraction for a beginner to understand the workflow of the mechanisms and how they interact with other mechanims within the OS. Students are often clueless about the internal flow of the mechanisms.

** Purpose
We primarily aim at bringing an in depth understanding of OS mechanisms and to introduce the student to the ideology of viewing a system as a transitional state model with simply changes depending on the action taken by the user or any other internal actions.

** Activities
- The student is going to play different roles at different times during the whole simulation. The roles played by the student are mainly 'User', 'Hardware', and 'Kernel', 'scheduler' etc.
- Aided with the prompts and feedbacks provided as a response to their previous actions, the student needs to perform right actions to succesfully do context switch between two process.

** Constraints
- The experiments don't have access to variety of actions during the simulations.
- The experiments are designed based on the Linux OS.

** Outcomes
- Student will be able to appreciate how different actions perfromed by different modes and subsytems operate together to complete the task of in the OS.
- To develope an high level abstract overview of the actors interacting in the OS.
- Understanding these dynamic systems in the form of transition states.
